version: '3.8'
services:
  parser:
    container_name: app_parser
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    networks:
      - "fullstack"
  db:
    container_name: app_db
    platform: linux/x86_64
    image: mysql:8.0
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: "go_api"
      MYSQL_USER: "go"
      MYSQL_PASSWORD: "12345678"
#    command: mysql -u root # здесь можно вставить команды с миграциями, но можно и просто дамп грузить
    volumes:
#      - ../../../../database:/var/lib/mysql
      - database:/var/lib/mysql
    networks:
      - "fullstack"
      - localhost
volumes:
  database:
networks:
  fullstack:
    driver: bridge
  localhost:
    driver: bridge
