// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeUserServer is an autogenerated mock type for the UnsafeUserServer type
type UnsafeUserServer struct {
	mock.Mock
}

// mustEmbedUnimplementedUserServer provides a mock function with given fields:
func (_m *UnsafeUserServer) mustEmbedUnimplementedUserServer() {
	_m.Called()
}

// NewUnsafeUserServer creates a new instance of UnsafeUserServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeUserServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeUserServer {
	mock := &UnsafeUserServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
