// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeProductServer is an autogenerated mock type for the UnsafeProductServer type
type UnsafeProductServer struct {
	mock.Mock
}

// mustEmbedUnimplementedProductServer provides a mock function with given fields:
func (_m *UnsafeProductServer) mustEmbedUnimplementedProductServer() {
	_m.Called()
}

// NewUnsafeProductServer creates a new instance of UnsafeProductServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeProductServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeProductServer {
	mock := &UnsafeProductServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
