// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	proto "github.com/iamgadfly/go-echo-api/pkg/api/user_v1/proto"
)

// UserClient is an autogenerated mock type for the UserClient type
type UserClient struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, in, opts
func (_m *UserClient) Get(ctx context.Context, in *proto.UserIdRequest, opts ...grpc.CallOption) (*proto.UserResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *proto.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UserIdRequest, ...grpc.CallOption) (*proto.UserResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UserIdRequest, ...grpc.CallOption) *proto.UserResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.UserIdRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsers provides a mock function with given fields: ctx, in, opts
func (_m *UserClient) GetUsers(ctx context.Context, in *proto.EmptyParams, opts ...grpc.CallOption) (*proto.UserResponseList, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 *proto.UserResponseList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.EmptyParams, ...grpc.CallOption) (*proto.UserResponseList, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.EmptyParams, ...grpc.CallOption) *proto.UserResponseList); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.UserResponseList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.EmptyParams, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserClient creates a new instance of UserClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserClient {
	mock := &UserClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
