// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	vacancy "github.com/iamgadfly/go-echo-api/pkg/api/vacancy_v1/proto"
)

// VacancyClient is an autogenerated mock type for the VacancyClient type
type VacancyClient struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, in, opts
func (_m *VacancyClient) Create(ctx context.Context, in *vacancy.CreateRequest, opts ...grpc.CallOption) (*vacancy.VacancyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *vacancy.VacancyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *vacancy.CreateRequest, ...grpc.CallOption) (*vacancy.VacancyResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *vacancy.CreateRequest, ...grpc.CallOption) *vacancy.VacancyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vacancy.VacancyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *vacancy.CreateRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, in, opts
func (_m *VacancyClient) GetById(ctx context.Context, in *vacancy.GetByIdRequest, opts ...grpc.CallOption) (*vacancy.VacancyResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *vacancy.VacancyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *vacancy.GetByIdRequest, ...grpc.CallOption) (*vacancy.VacancyResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *vacancy.GetByIdRequest, ...grpc.CallOption) *vacancy.VacancyResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*vacancy.VacancyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *vacancy.GetByIdRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVacancyClient creates a new instance of VacancyClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVacancyClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *VacancyClient {
	mock := &VacancyClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
