server:
  AppVersion: 1.0.0
  Port: :8000
  PprofPort: :8888
  Mode: Development
  JwtSecretKey: fdjfkjdfkjsdf
  CookieName: jwt-token
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: false
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

mysql:
  MysqlHost: 127.0.0.1
  MysqlPort: 3306
  MysqlUser: go
  MysqlPassword: 12345678
  MysqlDbname: go_api
  MysqlConnect: root:@(127.0.0.1:3306)/go_api


cookie:
  Name: jwt-token
  MaxAge: 86400
  Secure: false
  HttpOnly: true

session:
  Name: session-id
  Prefix: api-session
  Expire: 3600
